
CREATE TABLE SALESLIST
	(
		NUM NUMBER(5) PRIMARY KEY,
		NAME VARCHAR2(30) REFERENCES USERLIST(NAME) ON DELETE SET NULL,
		MENU VARCHAR2(30),
		PRICE NUMBER(5,0),
		AMOUNT NUMBER(5,0),
		TOT NUMBER(5,0),
		REGDATE DATE
	);
S
	
CREATE SEQUENCE SALESLIST_SEQ;
	
CREATE TABLE USERLIST
	(
		NAME VARCHAR2(30) PRIMARY KEY,
		PHONE VARCHAR2(30),
		POINT NUMBER(5,0),
		INDATE DATE
	);
	
CREATE TABLE COUPON
	(
		COUNUM VARCHAR2(30) PRIMARY KEY,
		COUVAL VARCHAR2(30),
		SALEPRICE NUMBER(5,0),
		LASTDATE DATE
	);

CREATE TABLE STORAGE
	(	
		CNUM NUMBER(5,0),
		SNUM NUMBER(5,0) PRIMARY KEY,
		MNAME VARCHAR2(30) REFERENCES MARTERIAL(MNAME) ON DELETE SET NULL,
		SAMOUNT NUMBER(5,0),
		INPUTDATE DATE
	);
	
CREATE SEQUENCE STORAGE_SEQ;
	
CREATE TABLE MARTERIAL
	(
		INUM NUMBER(5,0) ,
		MNAME VARCHAR2(30) PRIMARY KEY,
		IAMOUNT NUMBER(5,0),
		IFROM VARCHAR2(30),
		HOWUSE VARCHAR(30)
	);
CREATE SEQUENCE MARTERIAL_SEQ;
	